# Generated by Django 5.2.11 on 2026-02-26 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=60, unique=True)),
                ('fecha_recepcion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad', models.FloatField()),
                ('ubicacion_actual', models.CharField(choices=[('BODEGA', 'Bodega'), ('COCINA_FRIA', 'Cocina Fría'), ('COCINA_CALIENTE', 'Cocina Caliente'), ('REPOSTERIA', 'Repostería'), ('LINEA', 'Línea (Servicio)')], default='BODEGA', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CONSUMIDO', 'Consumido'), ('VENCIDO', 'Vencido'), ('DESCARTADO', 'Descartado')], default='ACTIVO', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_medida', models.CharField(choices=[('KG', 'Kilogramos'), ('G', 'Gramos'), ('L', 'Litros'), ('ML', 'Mililitros'), ('UN', 'Unidades'), ('CAJA', 'Cajas')], default='KG', max_length=5)),
                ('temperatura_min', models.FloatField(blank=True, help_text='°C (opcional)', null=True)),
                ('temperatura_max', models.FloatField(blank=True, help_text='°C (opcional)', null=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(blank=True, max_length=12)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoTrazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.CharField(choices=[('BODEGA', 'Bodega'), ('COCINA_FRIA', 'Cocina Fría'), ('COCINA_CALIENTE', 'Cocina Caliente'), ('REPOSTERIA', 'Repostería'), ('LINEA', 'Línea (Servicio)')], max_length=20)),
                ('hacia', models.CharField(choices=[('BODEGA', 'Bodega'), ('COCINA_FRIA', 'Cocina Fría'), ('COCINA_CALIENTE', 'Cocina Caliente'), ('REPOSTERIA', 'Repostería'), ('LINEA', 'Línea (Servicio)')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.CharField(blank=True, max_length=80)),
                ('observaciones', models.TextField(blank=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.lote')),
            ],
            options={
                'verbose_name': 'Movimiento de Trazabilidad',
                'verbose_name_plural': 'Movimientos de Trazabilidad',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='lote',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='inventario.proveedor'),
        ),
    ]
