# Generated by Django 5.2.11 on 2026-02-26 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='lotes_padres',
            field=models.ManyToManyField(blank=True, related_name='lotes_hijos', to='inventario.lote', verbose_name='Lotes de origen (insumos)'),
        ),
        migrations.AddField(
            model_name='lote',
            name='numero_guia',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nº Guía / Factura'),
        ),
        migrations.AddField(
            model_name='lote',
            name='numero_lote_proveedor',
            field=models.CharField(blank=True, max_length=80, verbose_name='Lote del Proveedor'),
        ),
        migrations.AddField(
            model_name='lote',
            name='proceso',
            field=models.CharField(choices=[('RECEPCION', 'Recepción de Bodega'), ('MARINADO', 'Marinado'), ('PORCIONADO', 'Porcionado'), ('COCCION', 'Cocción'), ('PREPARACION', 'Preparación / Mezcla'), ('HORNEADO', 'Horneado'), ('ENFRIADO', 'Enfriado'), ('OTRO', 'Otro')], default='RECEPCION', max_length=20, verbose_name='Proceso de origen'),
        ),
        migrations.AddField(
            model_name='lote',
            name='responsable_registro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Responsable de registro'),
        ),
        migrations.AddField(
            model_name='lote',
            name='temperatura_recepcion',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatura recepción (°C)'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='numero_lote',
            field=models.CharField(blank=True, max_length=60, unique=True),
        ),
        migrations.CreateModel(
            name='RegistroServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_servida', models.FloatField()),
                ('responsable', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='inventario.lote')),
            ],
            options={
                'verbose_name': 'Registro de Servicio',
                'verbose_name_plural': 'Registros de Servicio',
                'ordering': ['-fecha'],
            },
        ),
    ]
