# Generated by Django 5.2.11 on 2026-02-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_lote_lotes_padres_lote_numero_guia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientotrazabilidad',
            name='cantidad',
            field=models.FloatField(blank=True, null=True, verbose_name='Cantidad despachada'),
        ),
    ]
