# Generated by Django 5.2.11 on 2026-02-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_movimientotrazabilidad_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('completada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Tarea de Bodega',
                'verbose_name_plural': 'Tareas de Bodega',
                'ordering': ['completada', '-fecha_creacion'],
            },
        ),
    ]
