# Generated by Django 5.2.11 on 2026-02-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_tareabodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='precio_unitario',
            field=models.FloatField(default=0, help_text='Costo por unidad de medida'),
        ),
        migrations.AddField(
            model_name='lote',
            name='ubicacion_detalle',
            field=models.CharField(blank=True, help_text='Ej: Pasillo 2, Estante B', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('ABARROTES', 'Abarrotes'), ('CARNES', 'Carnes y Aves'), ('PESCADOS', 'Pescados y Mariscos'), ('LACTEOS', 'Lácteos y Huevos'), ('FRUTAS', 'Frutas y Verduras'), ('CONGELADOS', 'Congelados'), ('BEBIDAS', 'Bebidas'), ('LIMPIEZA', 'Aseo y Limpieza'), ('OTRO', 'Otros')], default='OTRO', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.FloatField(default=0, help_text='Alerta cuando el stock total baje de este valor'),
        ),
    ]
