# Generated by Django 5.2.11 on 2026-03-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_lote_precio_unitario_lote_ubicacion_detalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='ubicacion_actual',
            field=models.CharField(choices=[('BODEGA', 'Bodega'), ('COCINA_FRIA', 'Cocina Fría'), ('COCINA_CALIENTE', 'Cocina Caliente'), ('REPOSTERIA', 'Repostería'), ('LINEA', 'Línea (Servicio)'), ('CAMARA_1', 'Cámara 1'), ('CAMARA_2', 'Cámara 2'), ('CAMARA_3', 'Cámara 3'), ('CAMARA_4', 'Cámara 4'), ('CAMARA_5', 'Cámara 5'), ('OTRO', 'Otro')], default='BODEGA', max_length=30),
        ),
        migrations.AlterField(
            model_name='movimientotrazabilidad',
            name='desde',
            field=models.CharField(choices=[('BODEGA', 'Bodega'), ('COCINA_FRIA', 'Cocina Fría'), ('COCINA_CALIENTE', 'Cocina Caliente'), ('REPOSTERIA', 'Repostería'), ('LINEA', 'Línea (Servicio)'), ('CAMARA_1', 'Cámara 1'), ('CAMARA_2', 'Cámara 2'), ('CAMARA_3', 'Cámara 3'), ('CAMARA_4', 'Cámara 4'), ('CAMARA_5', 'Cámara 5'), ('OTRO', 'Otro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='movimientotrazabilidad',
            name='hacia',
            field=models.CharField(choices=[('BODEGA', 'Bodega'), ('COCINA_FRIA', 'Cocina Fría'), ('COCINA_CALIENTE', 'Cocina Caliente'), ('REPOSTERIA', 'Repostería'), ('LINEA', 'Línea (Servicio)'), ('CAMARA_1', 'Cámara 1'), ('CAMARA_2', 'Cámara 2'), ('CAMARA_3', 'Cámara 3'), ('CAMARA_4', 'Cámara 4'), ('CAMARA_5', 'Cámara 5'), ('OTRO', 'Otro')], max_length=30),
        ),
    ]
