# Generated by Django 5.2.11 on 2026-03-09 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_add_ubicacion_camaras_otro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTemperaturaCamara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camara', models.CharField(choices=[('CAMARA_1', 'Cámara 1'), ('CAMARA_2', 'Cámara 2'), ('CAMARA_3', 'Cámara 3'), ('CAMARA_4', 'Cámara 4'), ('CAMARA_5', 'Cámara 5')], max_length=20)),
                ('temperatura', models.FloatField(verbose_name='Temperatura (°C)')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Temperatura de Cámara',
                'verbose_name_plural': 'Registros de Temperatura de Cámaras',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
