# Generated by Django 5.2.11 on 2026-03-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_registroservicio_area_registroservicio_costo_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('CONSUMIDO', 'Consumido'), ('VENCIDO', 'Vencido'), ('DESCARTADO', 'Descartado')], db_index=True, default='ACTIVO', max_length=12),
        ),
    ]
