# Generated by Django 5.2.11 on 2026-04-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_lote_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('ABARROTES', 'Abarrotes'), ('CARNES', 'Carnes y Aves'), ('PESCADOS', 'Pescados y Mariscos'), ('LACTEOS', 'Lácteos y Huevos'), ('FRUTAS', 'Frutas y Verduras'), ('CONGELADOS', 'Congelados'), ('BEBIDAS', 'Bebidas'), ('LIMPIEZA', 'Aseo y Limpieza'), ('VESTUARIO', 'Vestuario / Ropa'), ('EPP', 'Elementos de Protección Personal'), ('OTRO', 'Otros')], default='OTRO', max_length=20),
        ),
    ]
