# Generated by Django 5.2.11 on 2026-05-04 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_producto_talla_alter_producto_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='ubicacion_actual',
            field=models.CharField(choices=[('BODEGA', 'Bodega'), ('COCINA_FRIA', 'Cocina Fría'), ('COCINA_CALIENTE', 'Cocina Caliente'), ('REPOSTERIA', 'Repostería'), ('PANADERIA', 'Panadería'), ('COLACION', 'Colación'), ('LINEA', 'Línea (Servicio)'), ('OTRO', 'Otro')], default='BODEGA', max_length=30),
        ),
        migrations.AlterField(
            model_name='movimientotrazabilidad',
            name='desde',
            field=models.CharField(choices=[('BODEGA', 'Bodega'), ('COCINA_FRIA', 'Cocina Fría'), ('COCINA_CALIENTE', 'Cocina Caliente'), ('REPOSTERIA', 'Repostería'), ('PANADERIA', 'Panadería'), ('COLACION', 'Colación'), ('LINEA', 'Línea (Servicio)'), ('OTRO', 'Otro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='movimientotrazabilidad',
            name='hacia',
            field=models.CharField(choices=[('BODEGA', 'Bodega'), ('COCINA_FRIA', 'Cocina Fría'), ('COCINA_CALIENTE', 'Cocina Caliente'), ('REPOSTERIA', 'Repostería'), ('PANADERIA', 'Panadería'), ('COLACION', 'Colación'), ('LINEA', 'Línea (Servicio)'), ('OTRO', 'Otro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='registroservicio',
            name='area',
            field=models.CharField(choices=[('BODEGA', 'Bodega'), ('COCINA_FRIA', 'Cocina Fría'), ('COCINA_CALIENTE', 'Cocina Caliente'), ('REPOSTERIA', 'Repostería'), ('PANADERIA', 'Panadería'), ('COLACION', 'Colación'), ('LINEA', 'Línea (Servicio)'), ('OTRO', 'Otro')], default='LINEA', max_length=30),
        ),
        migrations.AlterField(
            model_name='registroservicio',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
