# Generated by Django 5.2.11 on 2026-08-03 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_alter_lote_ubicacion_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroservicio',
            name='lote_codigo',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código de Lote Original'),
        ),
        migrations.AddField(
            model_name='registroservicio',
            name='producto_categoria',
            field=models.CharField(blank=True, max_length=20, verbose_name='Categoría del Producto'),
        ),
        migrations.AddField(
            model_name='registroservicio',
            name='producto_nombre',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre del Producto Histórico'),
        ),
        migrations.AddField(
            model_name='registroservicio',
            name='producto_talla',
            field=models.CharField(blank=True, max_length=50, verbose_name='Talla'),
        ),
        migrations.AddField(
            model_name='registroservicio',
            name='producto_unidad',
            field=models.CharField(blank=True, max_length=10, verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='registroservicio',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='inventario.lote'),
        ),
    ]
