# Generated by Django 4.2.11 on 2025-12-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0002_visitaatencion_especialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='dias_laborales',
        ),
    ]
