# Generated by Django 5.2.11 on 2026-02-26 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('cargo', models.CharField(max_length=100)),
                ('area', models.CharField(choices=[('BODEGA', 'Bodega'), ('COCINA', 'Cocina'), ('REPOSTERIA', 'Repostería'), ('LINEA', 'Línea'), ('ADMINISTRACION', 'Administración'), ('RRHH', 'Recursos Humanos'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('VACACIONES', 'En Vacaciones'), ('LICENCIA', 'Con Licencia'), ('FINIQUITADO', 'Finiquitado')], default='ACTIVO', max_length=15)),
                ('fecha_ingreso', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='empleados/fotos/')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CV', 'Currículum Vitae'), ('ANEXO', 'Anexo de Contrato'), ('FINIQUITO', 'Finiquito'), ('LIQUIDACION', 'Liquidación de Sueldo'), ('CONTRATO', 'Contrato'), ('OTRO', 'Otro')], max_length=15)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('archivo', models.FileField(upload_to='documentos_rrhh/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='rrhh.empleado')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VACACIONES', 'Vacaciones'), ('LICENCIA_MEDICA', 'Licencia Médica'), ('LICENCIA_MATERNIDAD', 'Licencia Maternal')], max_length=25)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias', to='rrhh.empleado')),
            ],
            options={
                'verbose_name': 'Período de Ausencia',
                'verbose_name_plural': 'Períodos de Ausencia',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
