# Generated by Django 5.2.11 on 2026-03-25 14:34

import coalfa.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_alter_documento_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('VACACIONES', 'En Vacaciones'), ('LICENCIA', 'Con Licencia'), ('FINIQUITADO', 'Finiquitado')], db_index=True, default='ACTIVO', max_length=15),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[coalfa.utils.rut_validator]),
        ),
    ]
