# Generated by Django 5.2.11 on 2026-03-31 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_alter_empleado_estado_alter_empleado_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoRRHH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', models.CharField(choices=[('PASAJES', 'Pago de Pasajes'), ('EPP', 'Artículos EPP'), ('CAJA_CHICA', 'Gastos de Caja (Caja Chica)'), ('EVENTO_COFFEE', 'Eventos / Coffee Break'), ('OTRO', 'Otros Gastos')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('responsable', models.CharField(blank=True, max_length=100)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='gastos_rrhh/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gasto RRHH',
                'verbose_name_plural': 'Gastos RRHH',
                'ordering': ['-fecha'],
            },
        ),
    ]
