# Generated by Django 5.2.11 on 2026-03-31 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0005_gastorrhh'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoEPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('stock', models.FloatField(default=0)),
                ('precio_unitario', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Producto EPP/Ropa',
                'verbose_name_plural': 'Inventario EPP/Ropa',
            },
        ),
        migrations.CreateModel(
            name='EntregaEPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('costo_total', models.DecimalField(decimal_places=0, editable=False, max_digits=12)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_epp', to='rrhh.empleado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.productoepp')),
            ],
            options={
                'verbose_name': 'Entrega de EPP',
                'verbose_name_plural': 'Entregas de EPP',
            },
        ),
    ]
