# Generated by Django 5.2.11 on 2026-04-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0006_productoepp_entregaepp'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoepp',
            name='talla',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='productoepp',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='productoepp',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='productoepp',
            unique_together={('nombre', 'talla')},
        ),
    ]
