# Generated by Django 5.2.11 on 2026-02-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coalfa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='solicitud_pendiente',
            field=models.BooleanField(default=False, verbose_name='Solicitud pendiente de aprobación'),
        ),
    ]
