# Generated by Django 5.2.11 on 2026-03-10 18:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coalfa', '0002_usuario_solicitud_pendiente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagen adjunta')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('nivel_importancia', models.CharField(choices=[('NORMAL', 'Normal'), ('DESTACADO', 'Destacado'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=15, verbose_name='Nivel de importancia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Noticia / Anuncio',
                'verbose_name_plural': 'Noticias y Anuncios',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
