# Generated by Django 5.2.11 on 2026-03-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coalfa', '0003_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('RRHH', 'Recursos Humanos'), ('OPERACIONAL', 'Operacional'), ('GERENTE', 'Gerente')], default='RRHH', max_length=15, verbose_name='Rol'),
        ),
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
