# Generated by Django 5.2.11 on 2026-03-25 14:34

import coalfa.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coalfa', '0004_alter_usuario_rol_delete_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[coalfa.utils.rut_validator], verbose_name='RUT'),
        ),
    ]
