# Generated by Django 5.2.11 on 2026-08-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coalfa', '0005_alter_usuario_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('RRHH', 'Recursos Humanos'), ('OPERACIONAL', 'Operacional'), ('GERENTE', 'Gerente'), ('AUDITOR', 'Auditor (Solo Lectura)')], default='RRHH', max_length=15, verbose_name='Rol'),
        ),
    ]
